[package]
name = "chat-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image"] }
tokio = { version = "1.36.0", features = ["full"] }
chrono = "0.4.34"
